fix: setting deno version to v1.10.x
because error with v1.11.x 

Warning Implicitly using latest version (1.0.0) for https://deno.land/x/url_join/mod.ts
Download https://deno.land/x/url_join@1.0.0/mod.ts
error: Relative import path "cfb" not prefixed with / or ./ or ../ from "https://cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"
Error: Process completed with exit code 1.